apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-target
  namespace: kafka
spec:
  serviceName: postgres-target
  replicas: 1 # At least 2 for production HA
  selector:
    matchLabels:
      app: postgres-target
  template:
    metadata:
      labels:
        app: postgres-target
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "12345" # Insecure - Use secrets for production
            - name: POSTGRES_USER  # Provide username
              value: postgres # Default user - change if needed
            - name: POSTGRES_DB
              value: targetdb
          volumeMounts: # Keep this even without PV for emptyDir
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi # Adjust size, even for emptyDir
