#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgres-source-connector
#data:
#  config.json: |
#    {
#      "name": "postgres-source-connector",
#      "config": {
#        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
#        "tasks.max": "1",
#        "database.hostname": "postgres-source",
#        "database.port": "5432",
#        "database.user": "postgres",
#        "database.password": "12345",
#        "database.dbname" : "sourcedb",
#        "database.server.name": "postgres-source-server",
#        "plugin.name": "pgoutput",
#        "slot.name": "debezium_slot",
#        "publication.name": "dbz_publication",
#        "table.include.list": "public.*",
#        "tombstones.on.delete": "false",
#        "transforms": "unwrap",
#        "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
#        "transforms.unwrap.delete.handling.mode": "rewrite",
#        "transforms.unwrap.add.fields": "op,source.ts_ms",
#        "transforms.unwrap.drop.tombstones": "false",
#        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
#        "value.converter": "org.apache.kafka.connect.json.JsonConverter"
#
#
#      }
#    }
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgres-sink-connector
#data:
#  config.json: |
#    {
#      "name": "postgres-sink-connector",
#      "config": {
#        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
#        "tasks.max": "1",
#        "connection.url": "jdbc:postgresql://postgres-target:5432/targetdb",
#        "connection.user": "postgres",
#        "connection.password": "12345",
#        "topics": "postgres-source-server.public.*",
#        "auto.create": "true",
#        "auto.evolve": "true",
#        "insert.mode": "upsert",
#        "pk.mode": "record_key",
#        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
#        "value.converter": "org.apache.kafka.connect.json.JsonConverter"
#      }
#    }


